apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: my-app
    type: front-end
spec:
  containers:
    - name: mysql-container
      image: mysql:latest
      env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
      ports:
        - containerPort: 3306
