apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication
  labels:
    app: my-app
    type: front-end
spec:
  replicas: 3
  selector:
    app: mypod-app
    type: front-end
  template:
    metadata:
      labels:
        app: mypod-app
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
